### ISSUE TITLE
Add Spanish lang

### ISSUE THREAD

**Issue by alejopachons** [willianmano/moodle-block_mycertificates#5]
Hi @willianmano, i would like to add spanish translations in block_mycertificates.php

<?php
// This file is part of My Certificates block for Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * My certificates spanish language translation
 *
 * @package    block_mycertificates
 * @copyright  2020 Willian Mano - http://conecti.me
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'Mis certificados';
$string['mycertificates:addinstance'] = 'Agregar un nuevo bloque de Mis certificados';
$string['mycertificates:myaddinstance'] = 'Agregar un nuevo bloque de certificados al tablero';
$string['nohavecertificates'] = 'Aún no tienes certificados.';
$string['privacy:metadata'] = 'El bloque de certificados solo muestra los datos almacenados en otras ubicaciones.';

**Comment by willianmano** [comment]
@alejopachons you need to use Moodle Lang site to translate any plugin.
